List<String> educationLevels = [
  'Class 1',
  'Class 2',
  'Class 3',
  'Class 4',
  'Class 5',
  'Class 6',
  'Class 7',
  'Class 8',
  'Class 9',
  'Class 10',
  'Class 11',
  'Class 12',
  'Bachelor of Arts (BA)',
  'Bachelor of Science (BSc)',
  'Bachelor of Commerce (BCom)',
  'Bachelor of Engineering (BE)',
  'Bachelor of Technology (B.Tech)',
  'Bachelor of Education (B.Ed)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Computer Applications (BCA)',
  'Bachelor of Fine Arts (BFA)',
  'Bachelor of Medicine, Bachelor of Surgery (MBBS)',
  'Bachelor of Dental Surgery (BDS)',
  'Bachelor of Pharmacy (BPharm)',
  'Bachelor of Law (LLB)',
  'Bachelor of Architecture (B.Arch)',
  'Master of Arts (MA)',
  'Master of Science (MSc)',
  'Master of Commerce (MCom)',
  'Master of Business Administration (MBA)',
  'Master of Technology (M.Tech)',
  'Master of Engineering (ME)',
  'Master of Computer Applications (MCA)',
  'Master of Education (MEd)',
  'Master of Fine Arts (MFA)',
  'Master of Laws (LLM)',
  'Doctor of Philosophy (Ph.D.)',
  'Diploma Programs (Polytechnic, ITI, etc.)',
  'Vocational Training Programs',
  'Chartered Accountancy (CA)',
  'Company Secretary (CS)',
  'Cost and Management Accountancy (CMA)',
  'Chartered Financial Analyst (CFA)',
  'Actuarial Science',
  'Journalism and Mass Communication',
  'Hotel Management',
  'Fashion Designing',
  'Interior Designing',
  'Event Management',
];
