name: students
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.3+2
  fluttertoast: ^8.2.8
  page_transition: ^2.1.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  animations: ^2.0.11
  loading_animation_widget: ^1.3.0
  loading_btn: ^1.0.3
  webview_flutter: ^2.0.2
  pinput: ^5.0.0
  gif: ^2.3.0
  animated_bottom_navigation_bar: ^1.3.3
  circular_reveal_animation: ^2.0.1
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  transformable_list_view: ^0.6.0
  stylish_pull_to_refresh: ^1.1.0
  flutter_rating_bar: ^4.0.1
  chat_bubbles: any


  http: ^1.2.2
  url_launcher: ^6.3.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  path: ^1.9.0
  smart_auth: ^2.0.0
  hexcolor: ^3.0.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  image: ^4.2.0
  flutter_custom_tabs: ^2.1.0
  ribbon_widget: ^1.0.5

  app_settings: ^5.1.1
  geolocator: ^9.0.0

  firebase_core: ^3.6.0
  zego_uikit_prebuilt_call: ^4.16.2
  zego_uikit_signaling_plugin: ^2.8.4
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  flutter_html: ^3.0.0-beta.2
  animated_text_kit: ^4.2.2
  fuzzywuzzy: ^1.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  razorpay_flutter: ^1.3.7




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/ringtone/



